# Spam SMS Detection or Prediction 

In [1]:
#Loading the libraries
import pandas as pd
import numpy as np
import nltk
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\gaura\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\gaura\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [2]:
messages = pd.read_csv('SMSSpamCollection',sep='\t',names = ['Label','Message'])

In [3]:
messages.head(5)

Label                                            Message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [4]:
messages.tail(5)

Label                                        Message
5579  spam              Pay $2000 to grab the opportunity
5580  spam              Pay $2000 to grab the opportunity
5581  spam              Pay $2000 to grab the opportunity
5582  spam              Pay $2000 to grab the opportunity
5583  spam  hi teacher ji thank you for seeing my project

In [6]:
#Info about the data
messages.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5584 entries, 0 to 5583
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   Label    5584 non-null   object
 1   Message  5584 non-null   object
dtypes: object(2)
memory usage: 87.4+ KB


In [7]:
# Count the number of missing values in each column of the 'messages' DataFrame
messages.isnull().sum()

Label      0
Message    0
dtype: int64

In [8]:
# Get the shape of the DataFrame
messages.shape

(5584, 2)

In [9]:
#Target variables counts
messages['Label'].value_counts()

ham     4825
spam     759
Name: Label, dtype: int64

In [10]:
#Calculating length of message
mes_len=0
length=[]
for i in range(len(messages)):
    length.append(len(messages['Message'][i]))

In [11]:
#Adding Length column to the dataframe
messages['Length']=length

In [12]:
messages.head()

Label                                            Message  Length
0   ham  Go until jurong point, crazy.. Available only ...     111
1   ham                      Ok lar... Joking wif u oni...      29
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...     155
3   ham  U dun say so early hor... U c already then say...      49
4   ham  Nah I don't think he goes to usf, he lives aro...      61

In [13]:
import string
count=0                                        # Initialize a counter for punctuation characters
punct=[]                                       # Create an empty list to store punctuation counts for each message
for i in range(len(messages)):                 # Iterate through each message in the 'Message' column of the DataFrame
    for j in messages['Message'][i]:           # Iterate through each character in the message
        if j in string.punctuation:            # Check if the character is a punctuation character
            count+=1                 
    #print(count)
    punct.append(count)                  # Append the count of punctuation characters for this message to the 'punct' list
    count=0                                    # Reset the count for the next message
    

In [15]:
punct

[9,
 6,
 6,
 6,
 2,
 8,
 2,
 6,
 6,
 2,
 6,
 8,
 8,
 4,
 2,
 11,
 6,
 5,
 1,
 8,
 1,
 0,
 6,
 3,
 2,
 7,
 1,
 6,
 7,
 4,
 4,
 7,
 1,
 1,
 2,
 6,
 3,
 0,
 6,
 7,
 3,
 15,
 5,
 1,
 10,
 4,
 2,
 2,
 2,
 7,
 2,
 11,
 1,
 14,
 5,
 6,
 12,
 3,
 0,
 3,
 5,
 2,
 0,
 2,
 2,
 3,
 8,
 10,
 5,
 1,
 9,
 1,
 1,
 6,
 3,
 2,
 2,
 3,
 5,
 4,
 2,
 2,
 0,
 0,
 1,
 5,
 4,
 4,
 1,
 5,
 3,
 5,
 2,
 2,
 3,
 8,
 3,
 1,
 7,
 0,
 3,
 2,
 3,
 6,
 8,
 0,
 2,
 2,
 1,
 6,
 3,
 1,
 2,
 4,
 6,
 15,
 13,
 7,
 4,
 6,
 3,
 6,
 3,
 2,
 1,
 2,
 2,
 9,
 1,
 4,
 5,
 2,
 3,
 1,
 5,
 8,
 4,
 1,
 1,
 4,
 12,
 2,
 2,
 9,
 2,
 0,
 1,
 7,
 3,
 3,
 2,
 3,
 1,
 6,
 6,
 16,
 1,
 4,
 8,
 2,
 3,
 1,
 5,
 5,
 13,
 6,
 1,
 5,
 3,
 2,
 5,
 2,
 12,
 1,
 6,
 7,
 1,
 1,
 14,
 1,
 5,
 3,
 2,
 2,
 2,
 1,
 7,
 1,
 2,
 1,
 5,
 5,
 8,
 4,
 2,
 3,
 0,
 0,
 2,
 5,
 8,
 5,
 0,
 16,
 1,
 1,
 3,
 13,
 1,
 4,
 3,
 4,
 0,
 7,
 6,
 2,
 1,
 3,
 3,
 0,
 5,
 2,
 5,
 2,
 6,
 11,
 2,
 6,
 1,
 12,
 0,
 7,
 0,
 2,
 4,
 8,
 6,
 0,
 2,
 14,
 3,
 1,
 0,
 5,
 9,
 

In [16]:
messages["Punctuation"]=punct

# Normalization

In [900]:
#Regex
import re

#Stopwords
from nltk.corpus import stopwords

#Lemmatization
from nltk.stem import WordNetLemmatizer
#Creating object for Lemmatizer
lemmatizer = WordNetLemmatizer()

In [901]:
#Removal of extra characters and stop words and lemmatization
corpus = []

#Skipping the 0th index (it's of Label)
for i in range(0,len(messages)):
    words = re.sub('[^a-zA-Z]',' ',messages['Message'][i])
    words = words.lower()
    #Splits into list of words 
    words = words.split()
    
    #Lemmatizing the word and removing the stopwords
    words = [lemmatizer.lemmatize(word) for word in words if word not in set(stopwords.words('english'))]
    
    #Again join words to form sentences
    words = ' '.join(words)
    
    corpus.append(words)

In [902]:
#What's in Corpus
corpus[0]

'go jurong point crazy available bugis n great world la e buffet cine got amore wat'

In [903]:
messages['Message'] = corpus

In [904]:
messages.head()

Label                                            Message  Length  \
0   ham  go jurong point crazy available bugis n great ...     111   
1   ham                            ok lar joking wif u oni      29   
2  spam  free entry wkly comp win fa cup final tkts st ...     155   
3   ham                u dun say early hor u c already say      49   
4   ham                nah think go usf life around though      61   

   Punctuation  
0            9  
1            6  
2            6  
3            6  
4            2

In [905]:
spam_messages = messages[messages['Label'] == 'spam']
ham_messages = messages[messages['Label'] == 'ham']

In [906]:
spam_messages.head()

Label                                            Message  Length  \
2   spam  free entry wkly comp win fa cup final tkts st ...     155   
5   spam  freemsg hey darling week word back like fun st...     147   
8   spam  winner valued network customer selected receiv...     157   
9   spam  mobile month u r entitled update latest colour...     154   
11  spam  six chance win cash pound txt csh send cost p ...     136   

    Punctuation  
2             6  
5             8  
8             6  
9             2  
11            8

In [907]:
ham_messages.head()

Label                                            Message  Length  \
0   ham  go jurong point crazy available bugis n great ...     111   
1   ham                            ok lar joking wif u oni      29   
3   ham                u dun say early hor u c already say      49   
4   ham                nah think go usf life around though      61   
6   ham      even brother like speak treat like aid patent      77   

   Punctuation  
0            9  
1            6  
3            6  
4            2  
6            2

# Training and evaluating a model

In [908]:
X = messages['Message']

In [909]:
X.head()

0    go jurong point crazy available bugis n great ...
1                              ok lar joking wif u oni
2    free entry wkly comp win fa cup final tkts st ...
3                  u dun say early hor u c already say
4                  nah think go usf life around though
Name: Message, dtype: object

In [910]:
y = messages['Label']

In [911]:
y.head()

0     ham
1     ham
2    spam
3     ham
4     ham
Name: Label, dtype: object

In [912]:
from sklearn.model_selection import train_test_split

In [913]:
X_train , X_test , y_train , y_test = train_test_split(X , y, test_size = 0.33, random_state = 42)


# Feature extraction

In [915]:
from sklearn.feature_extraction.text import CountVectorizer

In [916]:
count_vect=CountVectorizer()

In [917]:
#transform the training text data 'X_train' into a matrix of word counts and convert it to a dense array representation.
X_train_count_vect=count_vect.fit_transform(X_train).toarray()

In [918]:
X_train_count_vect

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [919]:
X_train_count_vect.shape

(3741, 5790)

In [920]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [921]:
tfidf=TfidfVectorizer()

In [922]:
X_train_tfidf_vect=count_vect.fit_transform(X_train).toarray()

In [923]:
X_train_tfidf_vect

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [924]:
X_train_tfidf_vect.shape

(3741, 5790)

In [925]:
from sklearn.naive_bayes import MultinomialNB   #for text classification
from sklearn.pipeline import Pipeline

In [926]:
# Fit the pipeline (includes both text vectorization and model training)
text_mnb=Pipeline([('tfidf',TfidfVectorizer()),('mnb',MultinomialNB())]) 

In [927]:
#Now u can directly pass the X_train dataset.
text_mnb.fit(X_train,y_train)

Pipeline(steps=[('tfidf', TfidfVectorizer()), ('mnb', MultinomialNB())])

In [928]:
X_test.head()

3835                    watching tv lor nice one like lor
1033                                   happy new year man
79                         still looking job much ta earn
167     urgent trying contact last weekend draw show p...
453                   k k detail want transfer acc enough
Name: Message, dtype: object

In [929]:
y_preds_mnb=text_mnb.predict(X_test)

In [930]:
y_preds_mnb

array(['ham', 'ham', 'ham', ..., 'ham', 'ham', 'ham'], dtype='<U4')

In [931]:
# Calculate the accuracy score of the 'text_mnb' Multinomial Naive Bayes classifier on the training dataset 
text_mnb.score(X_train,y_train)

0.9772788024592355

In [932]:
# Calculate the accuracy score of the 'text_mnb' Multinomial Naive Bayes classifier on the testing dataset
text_mnb.score(X_test,y_test)

0.9641888225718936

In [933]:
from sklearn.metrics import confusion_matrix

In [934]:
print(confusion_matrix(y_test,y_preds_mnb))

[[1592    2]
 [  64  185]]


In [935]:
from sklearn.metrics import classification_report       #Report performance of a classification model

In [936]:
print(classification_report(y_test,y_preds_mnb))

              precision    recall  f1-score   support

         ham       0.96      1.00      0.98      1594
        spam       0.99      0.74      0.85       249

    accuracy                           0.96      1843
   macro avg       0.98      0.87      0.91      1843
weighted avg       0.97      0.96      0.96      1843



In [937]:
#from sklearn.svm import LinearSVC         #categorize data points into one of two classes e.g., spam vs. non-spam sms

In [938]:
#each tuple takes the name you decide , next you call what you want to occur
#text_svm=Pipeline([('tfidf',TfidfVectorizer()),('svm',LinearSVC())])

In [939]:
#Now u can directly pass the X_train dataset.
#text_svm.fit(X_train,y_train)

In [940]:
#X_test.head()

In [941]:
#y_preds_svm=text_svm.predict(X_test)

In [942]:
#Predictions of the test data
#y_preds_svm

In [943]:
#training score
#text_svm.score(X_train,y_train)*100

In [944]:
#Testing score
#text_svm.score(X_test,y_test)

In [945]:
#print(confusion_matrix(y_test,y_preds_svm))

In [946]:
#print(classification_report(y_test,y_preds_svm))

# Message(Spam or Ham)

In [947]:
def refined_text(text):
    #Removal of extra characters and stop words
    words = re.sub('[^a-zA-Z]',' ',text)
    words = words.lower()
    #Splits into list of words 
    words = words.split()

    #Lemmatizing the word and removing the stopwords
    words = [lemmatizer.lemmatize(word) for word in words if word not in set(stopwords.words('english'))]

    #Again join words to form sentences
    words = ' '.join(words)
    return words

In [948]:
def final_result(test):
    for i in text_mnb.predict(refined_word):
        if i=='ham':
            print("RELAX! This message is not a Spam")
            userinput=input('Do you want to report it as spam? (yes/no): ') #Prompt the user to report the message as spam
            if userinput == 'yes':                                            # If the user wants to report it as spam
                with open("SMSSpamCollection (1)", "a") as file:              # Append the message to dataset
                    file.write(f"\n{'spam'}\t{text}" )
                print('Message reported as spam.')   # Print a confirmation message
        else:
            print('ALERT!! This message might be spam.')# Iterate through predictions made by the 'text_mnb' model 
 

In [17]:
#Message to be checked whether spam or not
text =input('Enter your Message:- ')

Enter your Message:- To win free prize by giving OTP


In [962]:
refined_word = refined_text(text)

In [963]:
refined_word = [refined_word]

In [964]:
final_result1=final_result(refined_word)

ALERT!! This message might be spam.
